/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstantRouteImport } from './routes/instant'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops.index'
import { Route as InstantIndexRouteImport } from './routes/instant.index'
import { Route as DmsIndexRouteImport } from './routes/dms.index'
import { Route as CollabIndexRouteImport } from './routes/collab.index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkshopsNewRouteImport } from './routes/workshops.new'
import { Route as WorkshopsSlugRouteImport } from './routes/workshops.$slug'
import { Route as WorksNewRouteImport } from './routes/works.new'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as RedeemCodeRouteImport } from './routes/redeem.$code'
import { Route as MeEditRouteImport } from './routes/me.edit'
import { Route as InstantIdRouteImport } from './routes/instant.$id'
import { Route as DmsConversationIdRouteImport } from './routes/dms.$conversationId'
import { Route as CollabNewRouteImport } from './routes/collab.new'
import { Route as CollabSlugRouteImport } from './routes/collab.$slug'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminBadgesRouteImport } from './routes/admin.badges'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstantRoute = InstantRouteImport.update({
  id: '/instant',
  path: '/instant',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopsRoute,
} as any)
const InstantIndexRoute = InstantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstantRoute,
} as any)
const DmsIndexRoute = DmsIndexRouteImport.update({
  id: '/dms/',
  path: '/dms/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabIndexRoute = CollabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollabRoute,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitiesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkshopsNewRoute = WorkshopsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkshopsRoute,
} as any)
const WorkshopsSlugRoute = WorkshopsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkshopsRoute,
} as any)
const WorksNewRoute = WorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemCodeRoute = RedeemCodeRouteImport.update({
  id: '/redeem/$code',
  path: '/redeem/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MeEditRoute = MeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MeRoute,
} as any)
const InstantIdRoute = InstantIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InstantRoute,
} as any)
const DmsConversationIdRoute = DmsConversationIdRouteImport.update({
  id: '/dms/$conversationId',
  path: '/dms/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabNewRoute = CollabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollabRoute,
} as any)
const CollabSlugRoute = CollabSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollabRoute,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CitiesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/collab': typeof CollabRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/instant': typeof InstantRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/admin/badges': typeof AdminBadgesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/collab/$slug': typeof CollabSlugRoute
  '/collab/new': typeof CollabNewRoute
  '/dms/$conversationId': typeof DmsConversationIdRoute
  '/instant/$id': typeof InstantIdRoute
  '/me/edit': typeof MeEditRoute
  '/redeem/$code': typeof RedeemCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/new': typeof WorksNewRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/workshops/new': typeof WorkshopsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/collab/': typeof CollabIndexRoute
  '/dms/': typeof DmsIndexRoute
  '/instant/': typeof InstantIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/collab/$slug': typeof CollabSlugRoute
  '/collab/new': typeof CollabNewRoute
  '/dms/$conversationId': typeof DmsConversationIdRoute
  '/instant/$id': typeof InstantIdRoute
  '/me/edit': typeof MeEditRoute
  '/redeem/$code': typeof RedeemCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/new': typeof WorksNewRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/workshops/new': typeof WorkshopsNewRoute
  '/admin': typeof AdminIndexRoute
  '/cities': typeof CitiesIndexRoute
  '/collab': typeof CollabIndexRoute
  '/dms': typeof DmsIndexRoute
  '/instant': typeof InstantIndexRoute
  '/workshops': typeof WorkshopsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/collab': typeof CollabRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/instant': typeof InstantRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/admin/badges': typeof AdminBadgesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/collab/$slug': typeof CollabSlugRoute
  '/collab/new': typeof CollabNewRoute
  '/dms/$conversationId': typeof DmsConversationIdRoute
  '/instant/$id': typeof InstantIdRoute
  '/me/edit': typeof MeEditRoute
  '/redeem/$code': typeof RedeemCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/new': typeof WorksNewRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/workshops/new': typeof WorkshopsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/collab/': typeof CollabIndexRoute
  '/dms/': typeof DmsIndexRoute
  '/instant/': typeof InstantIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cities'
    | '/collab'
    | '/forgot-password'
    | '/gallery'
    | '/instant'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/workshops'
    | '/admin/badges'
    | '/checkout/return'
    | '/cities/$slug'
    | '/collab/$slug'
    | '/collab/new'
    | '/dms/$conversationId'
    | '/instant/$id'
    | '/me/edit'
    | '/redeem/$code'
    | '/u/$username'
    | '/works/$slug'
    | '/works/new'
    | '/workshops/$slug'
    | '/workshops/new'
    | '/admin/'
    | '/cities/'
    | '/collab/'
    | '/dms/'
    | '/instant/'
    | '/workshops/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/badges'
    | '/checkout/return'
    | '/cities/$slug'
    | '/collab/$slug'
    | '/collab/new'
    | '/dms/$conversationId'
    | '/instant/$id'
    | '/me/edit'
    | '/redeem/$code'
    | '/u/$username'
    | '/works/$slug'
    | '/works/new'
    | '/workshops/$slug'
    | '/workshops/new'
    | '/admin'
    | '/cities'
    | '/collab'
    | '/dms'
    | '/instant'
    | '/workshops'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cities'
    | '/collab'
    | '/forgot-password'
    | '/gallery'
    | '/instant'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/workshops'
    | '/admin/badges'
    | '/checkout/return'
    | '/cities/$slug'
    | '/collab/$slug'
    | '/collab/new'
    | '/dms/$conversationId'
    | '/instant/$id'
    | '/me/edit'
    | '/redeem/$code'
    | '/u/$username'
    | '/works/$slug'
    | '/works/new'
    | '/workshops/$slug'
    | '/workshops/new'
    | '/admin/'
    | '/cities/'
    | '/collab/'
    | '/dms/'
    | '/instant/'
    | '/workshops/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitiesRoute: typeof CitiesRouteWithChildren
  CollabRoute: typeof CollabRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  InstantRoute: typeof InstantRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkshopsRoute: typeof WorkshopsRouteWithChildren
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DmsConversationIdRoute: typeof DmsConversationIdRoute
  RedeemCodeRoute: typeof RedeemCodeRoute
  UUsernameRoute: typeof UUsernameRoute
  WorksSlugRoute: typeof WorksSlugRoute
  WorksNewRoute: typeof WorksNewRoute
  DmsIndexRoute: typeof DmsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instant': {
      id: '/instant'
      path: '/instant'
      fullPath: '/instant'
      preLoaderRoute: typeof InstantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/instant/': {
      id: '/instant/'
      path: '/'
      fullPath: '/instant/'
      preLoaderRoute: typeof InstantIndexRouteImport
      parentRoute: typeof InstantRoute
    }
    '/dms/': {
      id: '/dms/'
      path: '/dms'
      fullPath: '/dms/'
      preLoaderRoute: typeof DmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/': {
      id: '/collab/'
      path: '/'
      fullPath: '/collab/'
      preLoaderRoute: typeof CollabIndexRouteImport
      parentRoute: typeof CollabRoute
    }
    '/cities/': {
      id: '/cities/'
      path: '/'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workshops/new': {
      id: '/workshops/new'
      path: '/new'
      fullPath: '/workshops/new'
      preLoaderRoute: typeof WorkshopsNewRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/workshops/$slug': {
      id: '/workshops/$slug'
      path: '/$slug'
      fullPath: '/workshops/$slug'
      preLoaderRoute: typeof WorkshopsSlugRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/works/new': {
      id: '/works/new'
      path: '/works/new'
      fullPath: '/works/new'
      preLoaderRoute: typeof WorksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem/$code': {
      id: '/redeem/$code'
      path: '/redeem/$code'
      fullPath: '/redeem/$code'
      preLoaderRoute: typeof RedeemCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/edit': {
      id: '/me/edit'
      path: '/edit'
      fullPath: '/me/edit'
      preLoaderRoute: typeof MeEditRouteImport
      parentRoute: typeof MeRoute
    }
    '/instant/$id': {
      id: '/instant/$id'
      path: '/$id'
      fullPath: '/instant/$id'
      preLoaderRoute: typeof InstantIdRouteImport
      parentRoute: typeof InstantRoute
    }
    '/dms/$conversationId': {
      id: '/dms/$conversationId'
      path: '/dms/$conversationId'
      fullPath: '/dms/$conversationId'
      preLoaderRoute: typeof DmsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/new': {
      id: '/collab/new'
      path: '/new'
      fullPath: '/collab/new'
      preLoaderRoute: typeof CollabNewRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/$slug': {
      id: '/collab/$slug'
      path: '/$slug'
      fullPath: '/collab/$slug'
      preLoaderRoute: typeof CollabSlugRouteImport
      parentRoute: typeof CollabRoute
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBadgesRoute: AdminBadgesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitiesRouteChildren {
  CitiesSlugRoute: typeof CitiesSlugRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesSlugRoute: CitiesSlugRoute,
  CitiesIndexRoute: CitiesIndexRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface CollabRouteChildren {
  CollabSlugRoute: typeof CollabSlugRoute
  CollabNewRoute: typeof CollabNewRoute
  CollabIndexRoute: typeof CollabIndexRoute
}

const CollabRouteChildren: CollabRouteChildren = {
  CollabSlugRoute: CollabSlugRoute,
  CollabNewRoute: CollabNewRoute,
  CollabIndexRoute: CollabIndexRoute,
}

const CollabRouteWithChildren =
  CollabRoute._addFileChildren(CollabRouteChildren)

interface InstantRouteChildren {
  InstantIdRoute: typeof InstantIdRoute
  InstantIndexRoute: typeof InstantIndexRoute
}

const InstantRouteChildren: InstantRouteChildren = {
  InstantIdRoute: InstantIdRoute,
  InstantIndexRoute: InstantIndexRoute,
}

const InstantRouteWithChildren =
  InstantRoute._addFileChildren(InstantRouteChildren)

interface MeRouteChildren {
  MeEditRoute: typeof MeEditRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeEditRoute: MeEditRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface WorkshopsRouteChildren {
  WorkshopsSlugRoute: typeof WorkshopsSlugRoute
  WorkshopsNewRoute: typeof WorkshopsNewRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

const WorkshopsRouteChildren: WorkshopsRouteChildren = {
  WorkshopsSlugRoute: WorkshopsSlugRoute,
  WorkshopsNewRoute: WorkshopsNewRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}

const WorkshopsRouteWithChildren = WorkshopsRoute._addFileChildren(
  WorkshopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CitiesRoute: CitiesRouteWithChildren,
  CollabRoute: CollabRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  InstantRoute: InstantRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkshopsRoute: WorkshopsRouteWithChildren,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DmsConversationIdRoute: DmsConversationIdRoute,
  RedeemCodeRoute: RedeemCodeRoute,
  UUsernameRoute: UUsernameRoute,
  WorksSlugRoute: WorksSlugRoute,
  WorksNewRoute: WorksNewRoute,
  DmsIndexRoute: DmsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
