/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GRouteImport } from './routes/g'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops.index'
import { Route as WorkshopIndexRouteImport } from './routes/workshop.index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as DmsIndexRouteImport } from './routes/dms.index'
import { Route as CollabIndexRouteImport } from './routes/collab.index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkshopsNewRouteImport } from './routes/workshops.new'
import { Route as WorkshopsSlugRouteImport } from './routes/workshops.$slug'
import { Route as WorkshopIdRouteImport } from './routes/workshop.$id'
import { Route as WorksNewRouteImport } from './routes/works.new'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'
import { Route as WTokenRouteImport } from './routes/w.$token'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as RedeemCodeRouteImport } from './routes/redeem.$code'
import { Route as MeTicketsRouteImport } from './routes/me.tickets'
import { Route as MeFriendsRouteImport } from './routes/me.friends'
import { Route as MeEditRouteImport } from './routes/me.edit'
import { Route as MeCollabsRouteImport } from './routes/me.collabs'
import { Route as MeBlockedRouteImport } from './routes/me.blocked'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as DmsConversationIdRouteImport } from './routes/dms.$conversationId'
import { Route as CollabNewRouteImport } from './routes/collab.new'
import { Route as CollabSlugRouteImport } from './routes/collab.$slug'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminLineupsRouteImport } from './routes/admin.lineups'
import { Route as AdminGrowthRouteImport } from './routes/admin.growth'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminGeoRouteImport } from './routes/admin.geo'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEngagementRouteImport } from './routes/admin.engagement'
import { Route as AdminBadgesRouteImport } from './routes/admin.badges'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as WorkshopsLobbyNewRouteImport } from './routes/workshops.lobby.new'
import { Route as WorkshopsSlugToolsRouteImport } from './routes/workshops.$slug.tools'
import { Route as WorkshopsSlugArchiveRouteImport } from './routes/workshops.$slug.archive'
import { Route as WorksInviteTokenRouteImport } from './routes/works.invite.$token'
import { Route as WorksCollabNewRouteImport } from './routes/works.collab.new'
import { Route as CollabClaimTokenRouteImport } from './routes/collab.claim.$token'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as WorkshopsSlugToolsToolRouteImport } from './routes/workshops.$slug.tools.$tool'
import { Route as GSlugEEventSlugRouteImport } from './routes/g.$slug.e.$eventSlug'
import { Route as ApiPublicWorkshopsSweepRouteImport } from './routes/api/public/workshops.sweep'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicEventsSweepRouteImport } from './routes/api/public/events.sweep'
import { Route as ApiPublicEventsReportSweepRouteImport } from './routes/api/public/events.report-sweep'
import { Route as ApiPublicEventsIdIcsRouteImport } from './routes/api/public/events.$id.ics'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GRoute = GRouteImport.update({
  id: '/g',
  path: '/g',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopsRoute,
} as any)
const WorkshopIndexRoute = WorkshopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const DmsIndexRoute = DmsIndexRouteImport.update({
  id: '/dms/',
  path: '/dms/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabIndexRoute = CollabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollabRoute,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitiesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkshopsNewRoute = WorkshopsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkshopsRoute,
} as any)
const WorkshopsSlugRoute = WorkshopsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkshopsRoute,
} as any)
const WorkshopIdRoute = WorkshopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorksNewRoute = WorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WTokenRoute = WTokenRouteImport.update({
  id: '/w/$token',
  path: '/w/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemCodeRoute = RedeemCodeRouteImport.update({
  id: '/redeem/$code',
  path: '/redeem/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MeTicketsRoute = MeTicketsRouteImport.update({
  id: '/me/tickets',
  path: '/me/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MeFriendsRoute = MeFriendsRouteImport.update({
  id: '/me/friends',
  path: '/me/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const MeEditRoute = MeEditRouteImport.update({
  id: '/me/edit',
  path: '/me/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MeCollabsRoute = MeCollabsRouteImport.update({
  id: '/me/collabs',
  path: '/me/collabs',
  getParentRoute: () => rootRouteImport,
} as any)
const MeBlockedRoute = MeBlockedRouteImport.update({
  id: '/me/blocked',
  path: '/me/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GRoute,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsConversationIdRoute = DmsConversationIdRouteImport.update({
  id: '/dms/$conversationId',
  path: '/dms/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabNewRoute = CollabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollabRoute,
} as any)
const CollabSlugRoute = CollabSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollabRoute,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CitiesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLineupsRoute = AdminLineupsRouteImport.update({
  id: '/lineups',
  path: '/lineups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrowthRoute = AdminGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeoRoute = AdminGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngagementRoute = AdminEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const WorkshopsLobbyNewRoute = WorkshopsLobbyNewRouteImport.update({
  id: '/lobby/new',
  path: '/lobby/new',
  getParentRoute: () => WorkshopsRoute,
} as any)
const WorkshopsSlugToolsRoute = WorkshopsSlugToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => WorkshopsSlugRoute,
} as any)
const WorkshopsSlugArchiveRoute = WorkshopsSlugArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => WorkshopsSlugRoute,
} as any)
const WorksInviteTokenRoute = WorksInviteTokenRouteImport.update({
  id: '/works/invite/$token',
  path: '/works/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksCollabNewRoute = WorksCollabNewRouteImport.update({
  id: '/works/collab/new',
  path: '/works/collab/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabClaimTokenRoute = CollabClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => CollabRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const WorkshopsSlugToolsToolRoute = WorkshopsSlugToolsToolRouteImport.update({
  id: '/$tool',
  path: '/$tool',
  getParentRoute: () => WorkshopsSlugToolsRoute,
} as any)
const GSlugEEventSlugRoute = GSlugEEventSlugRouteImport.update({
  id: '/e/$eventSlug',
  path: '/e/$eventSlug',
  getParentRoute: () => GSlugRoute,
} as any)
const ApiPublicWorkshopsSweepRoute = ApiPublicWorkshopsSweepRouteImport.update({
  id: '/api/public/workshops/sweep',
  path: '/api/public/workshops/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEventsSweepRoute = ApiPublicEventsSweepRouteImport.update({
  id: '/api/public/events/sweep',
  path: '/api/public/events/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsReportSweepRoute =
  ApiPublicEventsReportSweepRouteImport.update({
    id: '/api/public/events/report-sweep',
    path: '/api/public/events/report-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEventsIdIcsRoute = ApiPublicEventsIdIcsRouteImport.update({
  id: '/api/public/events/$id/ics',
  path: '/api/public/events/$id/ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/collab': typeof CollabRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/g': typeof GRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/workshops': typeof WorkshopsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/lineups': typeof AdminLineupsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/collab/$slug': typeof CollabSlugRoute
  '/collab/new': typeof CollabNewRoute
  '/dms/$conversationId': typeof DmsConversationIdRoute
  '/e/$code': typeof ECodeRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/me/blocked': typeof MeBlockedRoute
  '/me/collabs': typeof MeCollabsRoute
  '/me/edit': typeof MeEditRoute
  '/me/friends': typeof MeFriendsRoute
  '/me/tickets': typeof MeTicketsRoute
  '/redeem/$code': typeof RedeemCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/w/$token': typeof WTokenRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/new': typeof WorksNewRoute
  '/workshop/$id': typeof WorkshopIdRoute
  '/workshops/$slug': typeof WorkshopsSlugRouteWithChildren
  '/workshops/new': typeof WorkshopsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/collab/': typeof CollabIndexRoute
  '/dms/': typeof DmsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/me/': typeof MeIndexRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/collab/claim/$token': typeof CollabClaimTokenRoute
  '/works/collab/new': typeof WorksCollabNewRoute
  '/works/invite/$token': typeof WorksInviteTokenRoute
  '/workshops/$slug/archive': typeof WorkshopsSlugArchiveRoute
  '/workshops/$slug/tools': typeof WorkshopsSlugToolsRouteWithChildren
  '/workshops/lobby/new': typeof WorkshopsLobbyNewRoute
  '/api/public/events/report-sweep': typeof ApiPublicEventsReportSweepRoute
  '/api/public/events/sweep': typeof ApiPublicEventsSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/workshops/sweep': typeof ApiPublicWorkshopsSweepRoute
  '/g/$slug/e/$eventSlug': typeof GSlugEEventSlugRoute
  '/workshops/$slug/tools/$tool': typeof WorkshopsSlugToolsToolRoute
  '/api/public/events/$id/ics': typeof ApiPublicEventsIdIcsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/g': typeof GRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/lineups': typeof AdminLineupsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/collab/$slug': typeof CollabSlugRoute
  '/collab/new': typeof CollabNewRoute
  '/dms/$conversationId': typeof DmsConversationIdRoute
  '/e/$code': typeof ECodeRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/me/blocked': typeof MeBlockedRoute
  '/me/collabs': typeof MeCollabsRoute
  '/me/edit': typeof MeEditRoute
  '/me/friends': typeof MeFriendsRoute
  '/me/tickets': typeof MeTicketsRoute
  '/redeem/$code': typeof RedeemCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/w/$token': typeof WTokenRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/new': typeof WorksNewRoute
  '/workshop/$id': typeof WorkshopIdRoute
  '/workshops/$slug': typeof WorkshopsSlugRouteWithChildren
  '/workshops/new': typeof WorkshopsNewRoute
  '/admin': typeof AdminIndexRoute
  '/cities': typeof CitiesIndexRoute
  '/collab': typeof CollabIndexRoute
  '/dms': typeof DmsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/me': typeof MeIndexRoute
  '/workshop': typeof WorkshopIndexRoute
  '/workshops': typeof WorkshopsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/collab/claim/$token': typeof CollabClaimTokenRoute
  '/works/collab/new': typeof WorksCollabNewRoute
  '/works/invite/$token': typeof WorksInviteTokenRoute
  '/workshops/$slug/archive': typeof WorkshopsSlugArchiveRoute
  '/workshops/$slug/tools': typeof WorkshopsSlugToolsRouteWithChildren
  '/workshops/lobby/new': typeof WorkshopsLobbyNewRoute
  '/api/public/events/report-sweep': typeof ApiPublicEventsReportSweepRoute
  '/api/public/events/sweep': typeof ApiPublicEventsSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/workshops/sweep': typeof ApiPublicWorkshopsSweepRoute
  '/g/$slug/e/$eventSlug': typeof GSlugEEventSlugRoute
  '/workshops/$slug/tools/$tool': typeof WorkshopsSlugToolsToolRoute
  '/api/public/events/$id/ics': typeof ApiPublicEventsIdIcsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cities': typeof CitiesRouteWithChildren
  '/collab': typeof CollabRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/g': typeof GRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/groups': typeof GroupsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/workshops': typeof WorkshopsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/lineups': typeof AdminLineupsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/collab/$slug': typeof CollabSlugRoute
  '/collab/new': typeof CollabNewRoute
  '/dms/$conversationId': typeof DmsConversationIdRoute
  '/e/$code': typeof ECodeRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/me/blocked': typeof MeBlockedRoute
  '/me/collabs': typeof MeCollabsRoute
  '/me/edit': typeof MeEditRoute
  '/me/friends': typeof MeFriendsRoute
  '/me/tickets': typeof MeTicketsRoute
  '/redeem/$code': typeof RedeemCodeRoute
  '/u/$username': typeof UUsernameRoute
  '/w/$token': typeof WTokenRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/new': typeof WorksNewRoute
  '/workshop/$id': typeof WorkshopIdRoute
  '/workshops/$slug': typeof WorkshopsSlugRouteWithChildren
  '/workshops/new': typeof WorkshopsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/collab/': typeof CollabIndexRoute
  '/dms/': typeof DmsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/me/': typeof MeIndexRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/collab/claim/$token': typeof CollabClaimTokenRoute
  '/works/collab/new': typeof WorksCollabNewRoute
  '/works/invite/$token': typeof WorksInviteTokenRoute
  '/workshops/$slug/archive': typeof WorkshopsSlugArchiveRoute
  '/workshops/$slug/tools': typeof WorkshopsSlugToolsRouteWithChildren
  '/workshops/lobby/new': typeof WorkshopsLobbyNewRoute
  '/api/public/events/report-sweep': typeof ApiPublicEventsReportSweepRoute
  '/api/public/events/sweep': typeof ApiPublicEventsSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/workshops/sweep': typeof ApiPublicWorkshopsSweepRoute
  '/g/$slug/e/$eventSlug': typeof GSlugEEventSlugRoute
  '/workshops/$slug/tools/$tool': typeof WorkshopsSlugToolsToolRoute
  '/api/public/events/$id/ics': typeof ApiPublicEventsIdIcsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cities'
    | '/collab'
    | '/forgot-password'
    | '/g'
    | '/gallery'
    | '/groups'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/refer'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/workshop'
    | '/workshops'
    | '/admin/audit'
    | '/admin/badges'
    | '/admin/engagement'
    | '/admin/events'
    | '/admin/geo'
    | '/admin/groups'
    | '/admin/growth'
    | '/admin/lineups'
    | '/admin/links'
    | '/admin/marketplace'
    | '/admin/moderation'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/users'
    | '/checkout/return'
    | '/cities/$slug'
    | '/collab/$slug'
    | '/collab/new'
    | '/dms/$conversationId'
    | '/e/$code'
    | '/g/$slug'
    | '/me/blocked'
    | '/me/collabs'
    | '/me/edit'
    | '/me/friends'
    | '/me/tickets'
    | '/redeem/$code'
    | '/u/$username'
    | '/w/$token'
    | '/works/$slug'
    | '/works/new'
    | '/workshop/$id'
    | '/workshops/$slug'
    | '/workshops/new'
    | '/admin/'
    | '/cities/'
    | '/collab/'
    | '/dms/'
    | '/groups/'
    | '/me/'
    | '/workshop/'
    | '/workshops/'
    | '/admin/users/$id'
    | '/collab/claim/$token'
    | '/works/collab/new'
    | '/works/invite/$token'
    | '/workshops/$slug/archive'
    | '/workshops/$slug/tools'
    | '/workshops/lobby/new'
    | '/api/public/events/report-sweep'
    | '/api/public/events/sweep'
    | '/api/public/payments/webhook'
    | '/api/public/workshops/sweep'
    | '/g/$slug/e/$eventSlug'
    | '/workshops/$slug/tools/$tool'
    | '/api/public/events/$id/ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/g'
    | '/gallery'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/refer'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/audit'
    | '/admin/badges'
    | '/admin/engagement'
    | '/admin/events'
    | '/admin/geo'
    | '/admin/groups'
    | '/admin/growth'
    | '/admin/lineups'
    | '/admin/links'
    | '/admin/marketplace'
    | '/admin/moderation'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/users'
    | '/checkout/return'
    | '/cities/$slug'
    | '/collab/$slug'
    | '/collab/new'
    | '/dms/$conversationId'
    | '/e/$code'
    | '/g/$slug'
    | '/me/blocked'
    | '/me/collabs'
    | '/me/edit'
    | '/me/friends'
    | '/me/tickets'
    | '/redeem/$code'
    | '/u/$username'
    | '/w/$token'
    | '/works/$slug'
    | '/works/new'
    | '/workshop/$id'
    | '/workshops/$slug'
    | '/workshops/new'
    | '/admin'
    | '/cities'
    | '/collab'
    | '/dms'
    | '/groups'
    | '/me'
    | '/workshop'
    | '/workshops'
    | '/admin/users/$id'
    | '/collab/claim/$token'
    | '/works/collab/new'
    | '/works/invite/$token'
    | '/workshops/$slug/archive'
    | '/workshops/$slug/tools'
    | '/workshops/lobby/new'
    | '/api/public/events/report-sweep'
    | '/api/public/events/sweep'
    | '/api/public/payments/webhook'
    | '/api/public/workshops/sweep'
    | '/g/$slug/e/$eventSlug'
    | '/workshops/$slug/tools/$tool'
    | '/api/public/events/$id/ics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cities'
    | '/collab'
    | '/forgot-password'
    | '/g'
    | '/gallery'
    | '/groups'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/refer'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/workshop'
    | '/workshops'
    | '/admin/audit'
    | '/admin/badges'
    | '/admin/engagement'
    | '/admin/events'
    | '/admin/geo'
    | '/admin/groups'
    | '/admin/growth'
    | '/admin/lineups'
    | '/admin/links'
    | '/admin/marketplace'
    | '/admin/moderation'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/users'
    | '/checkout/return'
    | '/cities/$slug'
    | '/collab/$slug'
    | '/collab/new'
    | '/dms/$conversationId'
    | '/e/$code'
    | '/g/$slug'
    | '/me/blocked'
    | '/me/collabs'
    | '/me/edit'
    | '/me/friends'
    | '/me/tickets'
    | '/redeem/$code'
    | '/u/$username'
    | '/w/$token'
    | '/works/$slug'
    | '/works/new'
    | '/workshop/$id'
    | '/workshops/$slug'
    | '/workshops/new'
    | '/admin/'
    | '/cities/'
    | '/collab/'
    | '/dms/'
    | '/groups/'
    | '/me/'
    | '/workshop/'
    | '/workshops/'
    | '/admin/users/$id'
    | '/collab/claim/$token'
    | '/works/collab/new'
    | '/works/invite/$token'
    | '/workshops/$slug/archive'
    | '/workshops/$slug/tools'
    | '/workshops/lobby/new'
    | '/api/public/events/report-sweep'
    | '/api/public/events/sweep'
    | '/api/public/payments/webhook'
    | '/api/public/workshops/sweep'
    | '/g/$slug/e/$eventSlug'
    | '/workshops/$slug/tools/$tool'
    | '/api/public/events/$id/ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitiesRoute: typeof CitiesRouteWithChildren
  CollabRoute: typeof CollabRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GRoute: typeof GRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ReferRoute: typeof ReferRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkshopRoute: typeof WorkshopRouteWithChildren
  WorkshopsRoute: typeof WorkshopsRouteWithChildren
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DmsConversationIdRoute: typeof DmsConversationIdRoute
  ECodeRoute: typeof ECodeRoute
  MeBlockedRoute: typeof MeBlockedRoute
  MeCollabsRoute: typeof MeCollabsRoute
  MeEditRoute: typeof MeEditRoute
  MeFriendsRoute: typeof MeFriendsRoute
  MeTicketsRoute: typeof MeTicketsRoute
  RedeemCodeRoute: typeof RedeemCodeRoute
  UUsernameRoute: typeof UUsernameRoute
  WTokenRoute: typeof WTokenRoute
  WorksSlugRoute: typeof WorksSlugRoute
  WorksNewRoute: typeof WorksNewRoute
  DmsIndexRoute: typeof DmsIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  WorksCollabNewRoute: typeof WorksCollabNewRoute
  WorksInviteTokenRoute: typeof WorksInviteTokenRoute
  ApiPublicEventsReportSweepRoute: typeof ApiPublicEventsReportSweepRoute
  ApiPublicEventsSweepRoute: typeof ApiPublicEventsSweepRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWorkshopsSweepRoute: typeof ApiPublicWorkshopsSweepRoute
  ApiPublicEventsIdIcsRoute: typeof ApiPublicEventsIdIcsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g': {
      id: '/g'
      path: '/g'
      fullPath: '/g'
      preLoaderRoute: typeof GRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/workshop/': {
      id: '/workshop/'
      path: '/'
      fullPath: '/workshop/'
      preLoaderRoute: typeof WorkshopIndexRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/dms/': {
      id: '/dms/'
      path: '/dms'
      fullPath: '/dms/'
      preLoaderRoute: typeof DmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/': {
      id: '/collab/'
      path: '/'
      fullPath: '/collab/'
      preLoaderRoute: typeof CollabIndexRouteImport
      parentRoute: typeof CollabRoute
    }
    '/cities/': {
      id: '/cities/'
      path: '/'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workshops/new': {
      id: '/workshops/new'
      path: '/new'
      fullPath: '/workshops/new'
      preLoaderRoute: typeof WorkshopsNewRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/workshops/$slug': {
      id: '/workshops/$slug'
      path: '/$slug'
      fullPath: '/workshops/$slug'
      preLoaderRoute: typeof WorkshopsSlugRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/workshop/$id': {
      id: '/workshop/$id'
      path: '/$id'
      fullPath: '/workshop/$id'
      preLoaderRoute: typeof WorkshopIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/works/new': {
      id: '/works/new'
      path: '/works/new'
      fullPath: '/works/new'
      preLoaderRoute: typeof WorksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$token': {
      id: '/w/$token'
      path: '/w/$token'
      fullPath: '/w/$token'
      preLoaderRoute: typeof WTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem/$code': {
      id: '/redeem/$code'
      path: '/redeem/$code'
      fullPath: '/redeem/$code'
      preLoaderRoute: typeof RedeemCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/tickets': {
      id: '/me/tickets'
      path: '/me/tickets'
      fullPath: '/me/tickets'
      preLoaderRoute: typeof MeTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/friends': {
      id: '/me/friends'
      path: '/me/friends'
      fullPath: '/me/friends'
      preLoaderRoute: typeof MeFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/edit': {
      id: '/me/edit'
      path: '/me/edit'
      fullPath: '/me/edit'
      preLoaderRoute: typeof MeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/collabs': {
      id: '/me/collabs'
      path: '/me/collabs'
      fullPath: '/me/collabs'
      preLoaderRoute: typeof MeCollabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/blocked': {
      id: '/me/blocked'
      path: '/me/blocked'
      fullPath: '/me/blocked'
      preLoaderRoute: typeof MeBlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof GRoute
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms/$conversationId': {
      id: '/dms/$conversationId'
      path: '/dms/$conversationId'
      fullPath: '/dms/$conversationId'
      preLoaderRoute: typeof DmsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/new': {
      id: '/collab/new'
      path: '/new'
      fullPath: '/collab/new'
      preLoaderRoute: typeof CollabNewRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/$slug': {
      id: '/collab/$slug'
      path: '/$slug'
      fullPath: '/collab/$slug'
      preLoaderRoute: typeof CollabSlugRouteImport
      parentRoute: typeof CollabRoute
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lineups': {
      id: '/admin/lineups'
      path: '/lineups'
      fullPath: '/admin/lineups'
      preLoaderRoute: typeof AdminLineupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/growth': {
      id: '/admin/growth'
      path: '/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AdminGrowthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geo': {
      id: '/admin/geo'
      path: '/geo'
      fullPath: '/admin/geo'
      preLoaderRoute: typeof AdminGeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engagement': {
      id: '/admin/engagement'
      path: '/engagement'
      fullPath: '/admin/engagement'
      preLoaderRoute: typeof AdminEngagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workshops/lobby/new': {
      id: '/workshops/lobby/new'
      path: '/lobby/new'
      fullPath: '/workshops/lobby/new'
      preLoaderRoute: typeof WorkshopsLobbyNewRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/workshops/$slug/tools': {
      id: '/workshops/$slug/tools'
      path: '/tools'
      fullPath: '/workshops/$slug/tools'
      preLoaderRoute: typeof WorkshopsSlugToolsRouteImport
      parentRoute: typeof WorkshopsSlugRoute
    }
    '/workshops/$slug/archive': {
      id: '/workshops/$slug/archive'
      path: '/archive'
      fullPath: '/workshops/$slug/archive'
      preLoaderRoute: typeof WorkshopsSlugArchiveRouteImport
      parentRoute: typeof WorkshopsSlugRoute
    }
    '/works/invite/$token': {
      id: '/works/invite/$token'
      path: '/works/invite/$token'
      fullPath: '/works/invite/$token'
      preLoaderRoute: typeof WorksInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/collab/new': {
      id: '/works/collab/new'
      path: '/works/collab/new'
      fullPath: '/works/collab/new'
      preLoaderRoute: typeof WorksCollabNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/claim/$token': {
      id: '/collab/claim/$token'
      path: '/claim/$token'
      fullPath: '/collab/claim/$token'
      preLoaderRoute: typeof CollabClaimTokenRouteImport
      parentRoute: typeof CollabRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/workshops/$slug/tools/$tool': {
      id: '/workshops/$slug/tools/$tool'
      path: '/$tool'
      fullPath: '/workshops/$slug/tools/$tool'
      preLoaderRoute: typeof WorkshopsSlugToolsToolRouteImport
      parentRoute: typeof WorkshopsSlugToolsRoute
    }
    '/g/$slug/e/$eventSlug': {
      id: '/g/$slug/e/$eventSlug'
      path: '/e/$eventSlug'
      fullPath: '/g/$slug/e/$eventSlug'
      preLoaderRoute: typeof GSlugEEventSlugRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/api/public/workshops/sweep': {
      id: '/api/public/workshops/sweep'
      path: '/api/public/workshops/sweep'
      fullPath: '/api/public/workshops/sweep'
      preLoaderRoute: typeof ApiPublicWorkshopsSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/sweep': {
      id: '/api/public/events/sweep'
      path: '/api/public/events/sweep'
      fullPath: '/api/public/events/sweep'
      preLoaderRoute: typeof ApiPublicEventsSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/report-sweep': {
      id: '/api/public/events/report-sweep'
      path: '/api/public/events/report-sweep'
      fullPath: '/api/public/events/report-sweep'
      preLoaderRoute: typeof ApiPublicEventsReportSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/$id/ics': {
      id: '/api/public/events/$id/ics'
      path: '/api/public/events/$id/ics'
      fullPath: '/api/public/events/$id/ics'
      preLoaderRoute: typeof ApiPublicEventsIdIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminEngagementRoute: typeof AdminEngagementRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGeoRoute: typeof AdminGeoRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminGrowthRoute: typeof AdminGrowthRoute
  AdminLineupsRoute: typeof AdminLineupsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBadgesRoute: AdminBadgesRoute,
  AdminEngagementRoute: AdminEngagementRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGeoRoute: AdminGeoRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminGrowthRoute: AdminGrowthRoute,
  AdminLineupsRoute: AdminLineupsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitiesRouteChildren {
  CitiesSlugRoute: typeof CitiesSlugRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesSlugRoute: CitiesSlugRoute,
  CitiesIndexRoute: CitiesIndexRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface CollabRouteChildren {
  CollabSlugRoute: typeof CollabSlugRoute
  CollabNewRoute: typeof CollabNewRoute
  CollabIndexRoute: typeof CollabIndexRoute
  CollabClaimTokenRoute: typeof CollabClaimTokenRoute
}

const CollabRouteChildren: CollabRouteChildren = {
  CollabSlugRoute: CollabSlugRoute,
  CollabNewRoute: CollabNewRoute,
  CollabIndexRoute: CollabIndexRoute,
  CollabClaimTokenRoute: CollabClaimTokenRoute,
}

const CollabRouteWithChildren =
  CollabRoute._addFileChildren(CollabRouteChildren)

interface GSlugRouteChildren {
  GSlugEEventSlugRoute: typeof GSlugEEventSlugRoute
}

const GSlugRouteChildren: GSlugRouteChildren = {
  GSlugEEventSlugRoute: GSlugEEventSlugRoute,
}

const GSlugRouteWithChildren = GSlugRoute._addFileChildren(GSlugRouteChildren)

interface GRouteChildren {
  GSlugRoute: typeof GSlugRouteWithChildren
}

const GRouteChildren: GRouteChildren = {
  GSlugRoute: GSlugRouteWithChildren,
}

const GRouteWithChildren = GRoute._addFileChildren(GRouteChildren)

interface GroupsRouteChildren {
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface WorkshopRouteChildren {
  WorkshopIdRoute: typeof WorkshopIdRoute
  WorkshopIndexRoute: typeof WorkshopIndexRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopIdRoute: WorkshopIdRoute,
  WorkshopIndexRoute: WorkshopIndexRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

interface WorkshopsSlugToolsRouteChildren {
  WorkshopsSlugToolsToolRoute: typeof WorkshopsSlugToolsToolRoute
}

const WorkshopsSlugToolsRouteChildren: WorkshopsSlugToolsRouteChildren = {
  WorkshopsSlugToolsToolRoute: WorkshopsSlugToolsToolRoute,
}

const WorkshopsSlugToolsRouteWithChildren =
  WorkshopsSlugToolsRoute._addFileChildren(WorkshopsSlugToolsRouteChildren)

interface WorkshopsSlugRouteChildren {
  WorkshopsSlugArchiveRoute: typeof WorkshopsSlugArchiveRoute
  WorkshopsSlugToolsRoute: typeof WorkshopsSlugToolsRouteWithChildren
}

const WorkshopsSlugRouteChildren: WorkshopsSlugRouteChildren = {
  WorkshopsSlugArchiveRoute: WorkshopsSlugArchiveRoute,
  WorkshopsSlugToolsRoute: WorkshopsSlugToolsRouteWithChildren,
}

const WorkshopsSlugRouteWithChildren = WorkshopsSlugRoute._addFileChildren(
  WorkshopsSlugRouteChildren,
)

interface WorkshopsRouteChildren {
  WorkshopsSlugRoute: typeof WorkshopsSlugRouteWithChildren
  WorkshopsNewRoute: typeof WorkshopsNewRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
  WorkshopsLobbyNewRoute: typeof WorkshopsLobbyNewRoute
}

const WorkshopsRouteChildren: WorkshopsRouteChildren = {
  WorkshopsSlugRoute: WorkshopsSlugRouteWithChildren,
  WorkshopsNewRoute: WorkshopsNewRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
  WorkshopsLobbyNewRoute: WorkshopsLobbyNewRoute,
}

const WorkshopsRouteWithChildren = WorkshopsRoute._addFileChildren(
  WorkshopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CitiesRoute: CitiesRouteWithChildren,
  CollabRoute: CollabRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GRoute: GRouteWithChildren,
  GalleryRoute: GalleryRoute,
  GroupsRoute: GroupsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ReferRoute: ReferRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkshopRoute: WorkshopRouteWithChildren,
  WorkshopsRoute: WorkshopsRouteWithChildren,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DmsConversationIdRoute: DmsConversationIdRoute,
  ECodeRoute: ECodeRoute,
  MeBlockedRoute: MeBlockedRoute,
  MeCollabsRoute: MeCollabsRoute,
  MeEditRoute: MeEditRoute,
  MeFriendsRoute: MeFriendsRoute,
  MeTicketsRoute: MeTicketsRoute,
  RedeemCodeRoute: RedeemCodeRoute,
  UUsernameRoute: UUsernameRoute,
  WTokenRoute: WTokenRoute,
  WorksSlugRoute: WorksSlugRoute,
  WorksNewRoute: WorksNewRoute,
  DmsIndexRoute: DmsIndexRoute,
  MeIndexRoute: MeIndexRoute,
  WorksCollabNewRoute: WorksCollabNewRoute,
  WorksInviteTokenRoute: WorksInviteTokenRoute,
  ApiPublicEventsReportSweepRoute: ApiPublicEventsReportSweepRoute,
  ApiPublicEventsSweepRoute: ApiPublicEventsSweepRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWorkshopsSweepRoute: ApiPublicWorkshopsSweepRoute,
  ApiPublicEventsIdIcsRoute: ApiPublicEventsIdIcsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
